version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: pytest

  docker:
    docker:
      - image: docker:20.10.12
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t xRafay/devsecops-assignment2 .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push xRafay/devsecops-assignment2

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - docker:
          requires:
            - build
