version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest tests/
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Build Docker image
          command: docker build -t myapp:latest .
      - run:
          name: Run locally
          command: docker run -p 5000:5000 myapp:latest
workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build
      - deploy:
          requires:
            - build
